extends:
    - "stylelint-config-standard"

# See http://stylelint.io/user-guide/rules/
rules:
    # Color
    color-hex-length: short
    color-named: never
    color-no-invalid-hex: true

    # Font family
    font-family-name-quotes: always-unless-keyword

    # Font weight
    font-weight-notation: numeric

    # Function
    function-calc-no-unspaced-operator: true
    function-linear-gradient-no-nonstandard-direction: true
    function-name-case: lower
    function-url-quotes: always

    # String
    string-no-newline: true

    # Length
    length-zero-no-unit:
        - true
        - ignore: ["custom-properties"]

    # Unit
    unit-disallowed-list: ["pc", "in", "cm", "mm", "ex"]
    unit-no-unknown: true

    # Value
    value-keyword-case: lower
    value-no-vendor-prefix: true

    # Shorthand property
    shorthand-property-no-redundant-values: true

    # Property
    property-no-unknown: true
    property-no-vendor-prefix: true

    # Keyframe declaration
    keyframe-declaration-no-important: true

    # Declaration
    declaration-no-important: true

    # Declaration block
    declaration-block-no-duplicate-properties: true
    declaration-block-no-shorthand-property-overrides: true
    declaration-block-single-line-max-declarations: 3
    declaration-property-value-no-unknown: true

    # Block
    block-no-empty: true

    # Selector
    selector-max-id: 0
    selector-pseudo-element-colon-notation: double
    selector-pseudo-element-no-unknown: true
    selector-type-case: lower
    selector-max-type:
        - 0
        -   ignoreTypes:
                - a
                - body
                - button
                - dd
                - dt
                - em
                - html
                - i
                - iframe
                - img
                - li
                - mark
                - path
                - strong
                - svg
                - td
                - th
                - tr

    # Rule
    rule-empty-line-before:
        - always-multi-line
        -   except:
                - "after-single-line-comment"
                - "first-nested"
            ignore:
                - "after-comment"

    # Comments
    comment-no-empty: true

    # General / Sheet
    max-nesting-depth: 4
    no-duplicate-selectors: true
    no-unknown-animations: true
