parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
        jsx: true
        experimentalObjectRestSpread: true

env:
    browser: true
    commonjs: true
    es6: true
    jquery: true


globals:
    App: true
    Foundation: true
    require: false
    __DEBUG__: true

rules:
    brace-style:
        - error
        - allman
    indent:
        - error
        - tab
        - SwitchCase: 1
    keyword-spacing:
        - error
        - after: true
          before: true
    linebreak-style:
        - error
        - unix
    quotes:
        - warn
        - double
        - avoidEscape: true
          allowTemplateLiterals: true
    semi:
        - error
        - always
    space-before-function-paren:
        - error
        - always
